name: Automatic Approve
on:
  schedule:
    - cron: "*/* * * * *"
jobs:
  automatic-approve:
    name: Automatic Approve
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Approve
        uses: mheap/automatic-approve-action@v1
        with:
          token: ${{ secrets.PAT }}
          workflows: "auto.yml,validate.yml"
          dangerous_files: "index.html,dataset.json"
